apiVersion: batch/v1
kind: Job
metadata:
  name: trading-app-init
spec:
  template:
    metadata:
      labels:
        app: trading-app-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: container
          image: postgres:13.4
          command: ["bash", /app/init/init_db.sh]
          volumeMounts:
            - name: volume-sqls
              mountPath: /app/sqls
            - name: volume-init
              mountPath: /app/init
          env:
            - name: DB_HOST
              value: {{app_name}}-db
            - name: SQL_ROOT
              value: /app/sqls
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: postgres.{{app_name}}-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.{{app_name}}-db.credentials.postgresql.acid.zalan.do
                  key: password
      volumes:
        - name: volume-sqls
          configMap:
            name: trading-app-cm-sqls
        - name: volume-init
          configMap:
            name: trading-app-cm-init-db
